"""add phone verification and update account verification

Revision ID: 431feb6c7348
Revises: 4a8243ef9a7d
Create Date: 2026-09-10 20:07:05.116663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431feb6c7348'
down_revision = '4a8243ef9a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('phone_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('phone_otp_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('phone_otp_attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('phone_otp_last_sent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('phone_otp_last_sent_at')
        batch_op.drop_column('phone_otp_attempts')
        batch_op.drop_column('phone_otp_expires_at')
        batch_op.drop_column('phone_otp_hash')
        batch_op.drop_column('phone_verified')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
