"""add email OTP verification

Revision ID: 4a8243ef9a7d
Revises: a930521eb904
Create Date: 2026-09-10 19:15:51.978548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8243ef9a7d'
down_revision = 'a930521eb904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_otp_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('email_otp_attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('email_otp_last_sent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_otp_last_sent_at')
        batch_op.drop_column('email_otp_attempts')
        batch_op.drop_column('email_otp_expires_at')
        batch_op.drop_column('email_otp_hash')

    # ### end Alembic commands ###
