"""add seller reviews

Revision ID: 8c1771b9c887
Revises: eacdc2bd709e
Create Date: 2026-09-12 03:47:32.412567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1771b9c887'
down_revision = 'eacdc2bd709e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seller_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seller_reviews_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_reviews_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_reviews_seller_id'), ['seller_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seller_reviews_seller_id'))
        batch_op.drop_index(batch_op.f('ix_seller_reviews_listing_id'))
        batch_op.drop_index(batch_op.f('ix_seller_reviews_buyer_id'))

    op.drop_table('seller_reviews')
    # ### end Alembic commands ###
