"""add private listing verification information

Revision ID: eacdc2bd709e
Revises: 431feb6c7348
Create Date: 2026-09-11 23:36:11.583660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacdc2bd709e'
down_revision = '431feb6c7348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_verification_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('login_identifier', sa.Text(), nullable=True),
    sa.Column('login_method', sa.String(length=50), nullable=True),
    sa.Column('encrypted_login_secret', sa.Text(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_verification_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_verification_info_listing_id'), ['listing_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_verification_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_verification_info_listing_id'))

    op.drop_table('listing_verification_info')
    # ### end Alembic commands ###
